dist: jammy
language: cpp
compiler: gcc

env:
  jobs:
    - BUILD=Release
    - BUILD=Debug

addons:
  apt:
    packages:
      - cmake
      - g++
      - libboost-all-dev
      - libeigen3-dev
      - libarmadillo-dev
      - libhdf5-dev
      - libopenblas-dev
      - liblapack-dev

script:
  - cmake -S . -B build -DCMAKE_BUILD_TYPE=${BUILD}
  - cmake --build build --parallel 2
  - ctest --test-dir build --output-on-failure
